daysUntilClose: 14
responseRequiredLabel: need more info
closeComment: >
  This issue has been closed automatically because it needs more information and has not had recent activity. Please reach out if you have or find the answers we need so that we can investigate further.
