language: node_js

node_js:
- 'lts/*'

os:
- linux
- osx

before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
  fi
- chmod +x mvnw
- cd extension

install:
- npm install -g vsce
- npm install

script:
- gulp lint
- gulp build-server
- vsce package
- npm test --silent
