name: $(Date:yyyyMMdd).$(Rev:r)
variables:
  - name: Codeql.Enabled
    value: true
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
trigger:
  branches:
    include:
      - main
extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      os: linux
      name: 1ES_JavaTooling_Pool
      image: 1ES_JavaTooling_Ubuntu-2004
    sdl:
      sourceAnalysisPool:
        name: 1ES_JavaTooling_Pool
        image: 1ES_JavaTooling_Windows_2022
        os: windows
    customBuildTags:
      - MigrationTooling-mseng-VSJava-8790-Tool
    stages:
      - stage: Build
        jobs:
          - job: Job_1
            displayName: VSCode-Test-Runner-CI
            templateContext:
              outputs:
                - output: pipelineArtifact
                  artifactName: extension
                  targetPath: $(Build.ArtifactStagingDirectory)
                  displayName: "Publish Artifact: extension"
            steps:
              - checkout: self
                fetchTags: false
              - task: JavaToolInstaller@0
                displayName: Use Java 17
                inputs:
                  versionSpec: "17"
                  jdkArchitectureOption: x64
                  jdkSourceOption: PreInstalled
              - task: Npm@1
                displayName: npm install
                inputs:
                  verbose: false
              - task: Npm@1
                displayName: npm run lint
                inputs:
                  command: custom
                  verbose: false
                  customCommand: run lint
              - task: Npm@1
                displayName: npm run build-plugin
                inputs:
                  command: custom
                  verbose: false
                  customCommand: run build-plugin
              - task: Npm@1
                displayName: npm run vscode:prepublish
                inputs:
                  command: custom
                  verbose: false
                  customCommand: run vscode:prepublish
              - task: Bash@3
                displayName: vsce package
                inputs:
                  targetType: inline
                  script: npx @vscode/vsce@latest package
              - task: CopyFiles@2
                displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)"
                inputs:
                  Contents: "*.vsix"
                  TargetFolder: $(Build.ArtifactStagingDirectory)
